- name: My Arista Playbook
  hosts: switches
  gather_facts: false

  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
    ansible_become: yes
    ansible_become_method: enable
    ansible_user: admin
    ansible_ssh_pass: alta3

  tasks:
  - name: configure the login banner
    eos_banner:
      banner: login
      text: |
        Ready Player One!
      state: present

