---
- name: A simple file playbook
  hosts: planetexpress
  gather_facts: yes
  connection: ansible.builtin.ssh

  tasks:
    - name: Get home directory path
      set_fact:
        home_directory: "{{ ansible_env.HOME }}"

    - name: Write home directory path to a file
      copy:
        content: "{{ home_directory }}"
        dest: ~/output/path3.txt
